Projeto/apps/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),  # Página inicial do projeto
    path('cliente_login/', views.cliente_login, name='cliente_login'),  # Login do cliente
    path('cliente_cadastro/', views.cliente_cadastro, name='cliente_cadastro'),  # Cadastro do cliente
    path('servicos/', views.servicos, name='servicos'),  # Página de serviços (funcionário)
    path('detalhes_os/<int:os_id>/', views.detalhes_os, name='detalhes_os'),
    path('editar_os/<int:os_id>/', views.editar_os, name='editar_os'),
    path('funcionario_login/', views.funcionario_login, name='funcionario_login'),  # Login do funcionário
    path('logout/', views.logout_view, name='logout'),
    path('funcionario_cadastro/', views.funcionario_cadastro, name='funcionario_cadastro'),  # Cadastro do funcionário
    path('home_cliente/', views.home_cliente, name='home_cliente'),  # Cadastro do funcionário
    path('cadastrar_os_cliente/', views.cadastrar_os_cliente, name='cadastrar_os_cliente'),  # Cadastro OS por parte do cliente
    path('listar_os/', views.listar_os, name='listar_os'),  # Listas de todas as OS cadastradas 
    path('excluir_os/<int:pk>/', views.excluir_os, name='excluir_os'),
    path('avaliar_os/<int:os_id>/', views.avaliar_os, name='avaliar_os'),
    path('detalhes_os_cliente/<int:os_id>/', views.detalhes_os, name='detalhes_os_cliente'),
    path('funcionario_perfil/', views.funcionario_perfil, name='funcionario_perfil'),
    path('cliente_perfil/', views.cliente_perfil, name='cliente_perfil'),
    path('conta/excluir_conta/', views.excluir_conta, name='excluir_conta'),
    path('cliente_editar_perfil/', views.cliente_editar_perfil, name='cliente_editar_perfil'),
    path('funcionario_editar_perfil/', views.funcionario_editar_perfil, name='funcionario_editar_perfil'),
    path('lista_notifications/', views.lista_notifications, name='lista_notifications'),
]

Projeto/virtu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projeto/apps/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

# lembrando: SEMPRE que modificar ou acrescentar uma models a gnt tem q fazer os comandos:
# python manage.py makemigrations
# e em seguida:
# python manage.py migrate
# python manage.py runserver

class Perfil(models.Model):
    nome = models.CharField(max_length=255)
    username = models.CharField(max_length=30, unique=True)
    cpf = models.CharField(max_length=11)
    contato = models.CharField(max_length=11)

    funcionario = models.BooleanField()  # Campo booleano para distinguir entre cliente e funcionário

    def delete(self, *args, **kwargs):
        # Atualiza as tarefas antes de deletar o perfil
        OrdemServico.objects.filter(funcionario_responsavel=self).update(funcionario_responsavel=None, status='Enviada')
        super().delete(*args, **kwargs)


    def __str__(self):
        return (self.nome)


class OrdemServico(models.Model):
    STATUS_CHOICES = [
        ('Enviada', 'Ordem de serviço enviada'),
        ('Iniciada', 'Ordem de serviço iniciada'),
        ('Em_analise', 'Em análise'),
        ('Aguardando_peca', 'Aguardando peça'),
        ('Aguardando_reparo', 'Aguardando reparo'),
        ('Em_reparo', 'Em reparo'),
        ('Pronto', 'Pronto'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Enviada')

    TIPOS_ATENDIMENTO = [
        ('-', '-'),
        ('FON', 'Fora on site'),
        ('FB', 'Fora Balcão'),
        ('GS', 'Garantia serviço'),
        ('GB', 'Garantia balcão'),
        ('GON', 'Garantia on site'),
        ('GIN', 'Garantia instalação'),
        ('GRIN', 'Garantia reincidência'),
    ]
    tipo_atendimento = models.CharField(max_length=4, choices=TIPOS_ATENDIMENTO, default='-')

    aparelho = models.CharField(max_length=255)
    modelo = models.CharField(max_length=255)
    garantia = models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')])
    descricao_problema = models.CharField(max_length=255)
    perfil_os = models.ForeignKey('Perfil', on_delete=models.CASCADE, default=None)
    imagem = models.ImageField(upload_to='picture/', blank=True, null=True)
    avaliacao = models.IntegerField(blank=True, null=True)
    comentario_avaliacao = models.TextField(blank=True, null=True)

    funcionario_responsavel = models.ForeignKey('Perfil', on_delete=models.SET_NULL, null=True, blank=True, related_name='ordens_responsavel')

    mensagem_funcionario = models.TextField(blank=True, null=True)
    problema_detectado = models.TextField(blank=True, null=True)

    numero = models.CharField(max_length=10, unique=True)
    created_at = models.DateTimeField(default=datetime.now)  # Adiciona o campo de data de criação com um valor padrão

    def save(self, *args, **kwargs):
        if not self.numero:
            year = datetime.now().year
            prefix = str(year)[-2:]
            last_order = OrdemServico.objects.filter(numero__startswith=prefix).order_by('-numero').first()
            if last_order:
                last_number = int(last_order.numero[-3:])
                new_number = last_number + 1
            else:
                new_number = 1
            self.numero = f"{prefix}{new_number:03d}"
        super().save(*args, **kwargs)

    def detalhes(self):
        return {
            'aparelho': self.aparelho,
            'modelo': self.modelo,
            'garantia': 'Sim' if self.garantia else 'Não',
            'descricao_problema': self.descricao_problema,
            'cliente_nome': self.perfil_os.username if self.perfil_os else None,
            'cliente_cpf': self.perfil_os.cpf if self.perfil_os else None,
            'cliente_contato': self.perfil_os.contato if self.perfil_os else None,
            'status': self.get_status_display(),
            'mensagem_funcionario': self.mensagem_funcionario,
            'problema_detectado': self.problema_detectado,
            'tipo_atendimento': self.get_tipo_atendimento_display(),
        }

    def __str__(self):
        return self.aparelho

Projeto/apps/templates/apps/avaliar_os.html
{% extends 'global/base.html' %}

{% block content %}

<h1>Avaliar Ordem de Serviço</h1>
<form method="post" id="avaliacaoForm">
    {% csrf_token %}
    <div class="avaliacao-container">
        <ul class="avaliacao">
            <li class="star-icon {% if avaliacao >= 1 %}ativo{% endif %}" data-avaliacao="1"></li>
            <li class="star-icon {% if avaliacao >= 2 %}ativo{% endif %}" data-avaliacao="2"></li>
            <li class="star-icon {% if avaliacao >= 3 %}ativo{% endif %}" data-avaliacao="3"></li>
            <li class="star-icon {% if avaliacao >= 4 %}ativo{% endif %}" data-avaliacao="4"></li>
            <li class="star-icon {% if avaliacao >= 5 %}ativo{% endif %}" data-avaliacao="5"></li>
        </ul>
        <input type="hidden" id="avaliacao" name="avaliacao" value="{{ avaliacao }}">
        <div class="form-group">
            <label for="comentario_avaliacao">Comentário:</label>
            <textarea class="form-control" id="comentario_avaliacao" name="comentario_avaliacao" rows="3">{{ comentario_avaliacao }}</textarea>
        </div>
        <button id="avaliar" type="submit" class="btn btn-outline-secondary" onclick="window.location.href='home_cliente';">Avalie!</button>
    </div>
</form>

<script>
    var stars = document.querySelectorAll('.star-icon');
    var avaliacaoInput = document.getElementById('avaliacao');

    stars.forEach(function(star) {
        star.addEventListener('click', function() {
            stars.forEach(function(s) {
                s.classList.remove('ativo');
            });
            this.classList.add('ativo');
            avaliacaoInput.value = this.getAttribute('data-avaliacao');
        });
    });

    document.getElementById('avaliacaoForm').addEventListener('submit', function(e) {
        if (!avaliacaoInput.value) {
            e.preventDefault();
            alert('Por favor, selecione uma avaliação.');
        }
    });
</script>

{% endblock %}

Projeto/apps/templates/apps/cadastrar_os_cliente.html
{% extends 'global/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Novo Serviço</h1>
    <div class="card">
        <div class="elementos">
            <div class="forms">
                <label>Foto</label>
                <label class="picture" for="picture__input" tabIndex="0">
                    <span class="picture__image"></span>
                </label>
                <input type="file" name="picture__input" id="picture__input">
            </div>

            <div class="forms">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="aparelho" name="aparelho" placeholder="Tipo de aparelho" required>
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <input type="text" class="form-control" id="modelo" name="modelo" placeholder="Modelo" required>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <textarea type="text" class="form-control" id="descricao_problema" name="descricao_problema" rows="5" placeholder="Descreva seu problema..." required></textarea>
                </div>
            </div>

            <div class="forms">
                <div class="form-group text-center">
                    <label>Garantia:</label><br>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="garantia" id="garantia_sim" value="True" required>
                            <label class="form-check-label" for="garantia_sim">Sim</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="garantia" id="garantia_nao" value="False" required>
                            <label class="form-check-label" for="garantia_nao">Não</label>
                        </div>
                </div>      
            </div>
        </div>

        <div class="text-center">
            <button onclick="window.history.back()" class="btn btn-secondary">Cancelar</button>
            <input type="submit" value="Cadastrar" class="btn btn-primary">
        </div>
    </form>
</div>

<script>
    const inputFile = document.querySelector("#picture__input");
    const pictureImage = document.querySelector(".picture__image");
    const pictureImageTxt = "Escolha uma imagem";
    pictureImage.innerHTML = pictureImageTxt;

    inputFile.addEventListener("change", function (e) {
    const inputTarget = e.target;
    const file = inputTarget.files[0];

    if (file) {
        const reader = new FileReader();

        reader.addEventListener("load", function (e) {
        const readerTarget = e.target;

        const img = document.createElement("img");
        img.src = readerTarget.result;
        img.classList.add("picture__img");

        pictureImage.innerHTML = "";
        pictureImage.appendChild(img);
        });

        reader.readAsDataURL(file);
    } else {
        pictureImage.innerHTML = pictureImageTxt;
    }
    });
</script>
{% endblock %}

Projeto/apps/templates/apps/cliente_login.html
{% extends 'global/base_logins.html' %}
{% load static %}

{% block body %}
    <div class="container">
        <div class="div-img">
            <img src="{% static 'global/img/Vbox principal (3).png' %}" alt="Logo VBox">
        </div>
        <h2 id="h2_login">LOGIN CLIENTE</h2>

        <form class="login login-cliente" method="post">
            {% csrf_token %}
            
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <input type="text" id="username" name="username" placeholder="Username" required><br>
            
            <input type="password" id="senha" name="senha" placeholder="Senha" required><br><br>

            <input type='submit' value='ENTRAR' class='btn btn-light'>

        </form>
        <p><a href="{% url 'cliente_cadastro' %}">Não possui uma conta? Cadastre-se</a></p>
    </div>
{% endblock %}

Projeto/apps/templates/apps/cliente_perfil.html
{% extends 'global/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Meu Perfil</h1>
    <br>
    <p><strong>Nome:</strong> {{ nome_completo }}</p>
    <p><strong>Email:</strong> {{ email }}</p>
    <p><strong>CPF:</strong> {{ cpf }}</p>
    <p><strong>Contato:</strong> {{ contato }}</p>
    <a href="{% url 'cliente_editar_perfil' %}" class="btn btn-primary">Editar Perfil</a>
    <a href="{% url 'excluir_conta' %}" class="btn btn-danger">Excluir Conta</a>
</div>
{% endblock %}

Projeto/apps/templates/apps/detalhes_os.html
{% extends 'global/base.html' %}

{% block content %}

<div class="title_detalhes_os">
  <h5 class="card-title">ORDEM DE SERVIÇO: {{ numero_os }}</h5>
</div>
<div class="container-detalhes_os">
  <div class="card mb-3 mx-auto" style="max-width: 1350px">
    <h5>STATUS: <span class="dynamic-info">{{ detalhes_da_os.status }}</span></h5>
    <div class="row g-0">
      <div class="col-md-4">
        {% if os.imagem %}
          <img src="{{ os.imagem.url }}" class="card-img-top img-fluid rounded-start" alt="{{ os.descricao }}">
        {% else %}
          <svg
            class="bd-placeholder-img img-fluid rounded-start"
            width="100%"
            height="315"
            xmlns="http://www.w3.org/2000/svg"
            role="img"
            aria-label="Placeholder: Image"
            preserveAspectRatio="xMidYMid slice"
            focusable="false">
            <title>Placeholder</title>
            <rect width="100%" height="100%" fill="#868e96"></rect>
            <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image</text>
          </svg>
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body d-flex">
          <div class="ul-column flex-grow-1">
            <ul class="list-group">
              <li class="list-group-item">Aparelho: <span class="dynamic-info">{{ detalhes_da_os.aparelho }}</span></li>
              <li class="list-group-item">Data de Entrada: <span class="dynamic-info">{{ os.created_at|date:"d/m/Y" }}</span></li>
              <li class="list-group-item">Tipo de Produto: <span class="dynamic-info">{{ detalhes_da_os.modelo }}</span></li>
              <li class="list-group-item">Cliente: <span class="dynamic-info">{{ os.perfil_os.nome }}</span></li>
              <li class="list-group-item">Contato: <span class="dynamic-info">{{ os.perfil_os.contato }}</span></li>
              <li class="list-group-item">Tipo de Atendimento: <span class="dynamic-info">{{ detalhes_da_os.tipo_atendimento }}</span></li>
              <li class="list-group-item">Problema relatado: <span class="dynamic-info">{{ detalhes_da_os.descricao_problema }}</span></li>
              {% if os.status != 'Enviada' %}
                <li class="list-group-item">Técnico Responsável: <span class="dynamic-info">{{ funcionario_responsavel|default:"OS sem responsável" }}</span></li>
                <li class="list-group-item">Garantia: <span class="dynamic-info">{{ detalhes_da_os.garantia }}</span></li>
              {% endif %}
            </ul>
          </div>
          <div class="flex-shrink-0 ms-3">
            {% if os.status == 'Enviada' %}
              <form method="post" class="mt-3">
                {% csrf_token %}
                <button type="submit" class="btn btn-success" name="responsabilizar">Responsabilizar-se</button>
              </form>
            {% else %}
            <div class="box-mensagem-funcionario">
              <h6>Comentários para o Cliente:</h6>
              <div class="comment-bubble mt-3">
                <p>{{ detalhes_da_os.mensagem_funcionario|default:"Nenhum comentário feito" }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% if os.status == 'Pronto' %}
            <div class="details-page__info-actions">
                {% if os.avaliacao %}
                    <p id="avaliacao_detalhes">Avaliação do cliente: <span class="rating" data-rating="{{ os.avaliacao }}"></span></p>
                {% endif %}
            </div>
        {% endif %}
  </div>
</div>
<div class="btn-detalhes">
  <a href="{% url 'editar_os' os.id %}" class="btn btn-primary">Atualizar informações</a>
</div>
{% endif %}

<script type="text/javascript">
  function renderStars(rating) {
      let stars = '';
      for (let i = 0; i < 5; i++) {
          if (i < rating) {
              stars += '★'; // Filled star
          } else {
              stars += '☆'; // Empty star
          }
      }
      return stars;
  }

  window.onload = function() {
      var ratingElements = document.getElementsByClassName('rating');
      for (var i = 0; i < ratingElements.length; i++) {
          var ratingElement = ratingElements[i];
          var rating = ratingElement.getAttribute('data-rating');
          ratingElement.innerHTML = renderStars(rating);
      }
  }
</script>


{% endblock %}

Projeto/apps/templates/apps/detalhes_os_cliente.html
{% extends 'global/base.html' %}
{% load static %}

{% block content %}

<title>Detalhes da Ordem de Serviço</title>

<link rel="stylesheet" type="text/css" href="{% static 'css/details_page.css' %}">

<div class="container-detalhes_os">
    <div class="card mb-3 mx-auto" style="max-width: 1350px">
        <h5>STATUS: <span class="dynamic-info">{{ detalhes_da_os.status }}</span></h5>
        <div class="row g-0">
            <div class="col-md-4">
                {% if os.imagem %}
                    <img src="{{ os.imagem.url }}" class="card-img-top img-fluid rounded-start" alt="{{ os.descricao }}">
                {% else %}
                    <svg class="bd-placeholder-img img-fluid rounded-start" width="100%" height="315" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image" preserveAspectRatio="xMidYMid slice" focusable="false">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#868e96"></rect>
                        <text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image</text>
                    </svg>
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body d-flex">
                    <div class="ul-column flex-grow-1">
                        <ul class="list-group">
                            <li class="list-group-item">Número da OS: <span class="dynamic-info">{{ os.numero|default:"-" }}</span></li>
                            <li class="list-group-item">Data de Entrada: <span class="dynamic-info">{{ os.created_at|date:"d/m/Y" }}</span></li>
                            <li class="list-group-item">Tipo de Atendimento: <span class="dynamic-info">{{ os.tipo_atendimento }}</span></li>
                            <li id="status_os_detalhes_cliente" class="list-group-item">Status: <span class="dynamic-info">{{ os.status }}</span></li>
                            <li class="list-group-item">Contato: <span class="dynamic-info">{{ os.perfil_os.contato }}</span></li>
                            <li class="list-group-item">Tipo de Atendimento: <span class="dynamic-info">{{ detalhes_da_os.tipo_atendimento }}</span></li>
                            <li class="list-group-item">Problema relatado: <span class="dynamic-info">{{ detalhes_da_os.descricao_problema }}</span></li>
                            {% if os.status != 'Enviada' %}
                                <li class="list-group-item">Técnico Responsável: <span class="dynamic-info">{{ os.funcionario_responsavel|default:"OS sem responsável" }}</span></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="flex-shrink-0 ms-3">
                        <div class="box-mensagem-funcionario">
                            <h6>Comentários do Funcionário:</h6>
                            <div class="comment-bubble mt-3">
                                <p>{{ detalhes_da_os.mensagem_funcionario|default:"Nenhum comentário feito" }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if os.status == 'Pronto' %}
            <div class="details-page__info-actions">
                {% if os.avaliacao %}
                    <a href="{% url 'avaliar_os' os.id %}" id="avalie" class="btn btn-outline-secondary">Editar Avaliação</a>
                    <p>Sua avaliação: <span class="rating" data-rating="{{ os.avaliacao }}"></span></p>
                {% else %}
                    <a href="{% url 'avaliar_os' os.id %}" id="avalie" class="btn btn-outline-secondary">Avaliar Ordem de Serviço</a>
                {% endif %}
            </div>
        {% endif %}
    </div>
    {% if os.status != 'Enviada' %}
        <div class="details-page__status">
            <section class="step-wizard">
                <ul class="step-wizard-list">
                    <li class="step-wizard-item {% if os.status == 'Iniciada' %}current-item{% endif %}">
                        <span class="progress-count">1</span>
                        <span class="progress-label">Iniciada</span>
                    </li>
                    <li class="step-wizard-item {% if os.status == 'Em_analise' %}current-item{% endif %}">
                        <span class="progress-count">2</span>
                        <span class="progress-label">Em análise</span>
                    </li>
                    <li id="status_aguardando_peca" class="step-wizard-item {% if os.status == 'Aguardando_peca' %}current-item{% endif %}">
                        <span class="progress-count">3</span>
                        <span class="progress-label">Aguardando peça</span>
                    </li>
                    <li class="step-wizard-item {% if os.status == 'Aguardando_reparo' %}current-item{% endif %}">
                        <span class="progress-count">4</span>
                        <span class="progress-label">Aguardando reparo</span>
                    </li>
                    <li class="step-wizard-item {% if os.status == 'Em_reparo' %}current-item{% endif %}">
                        <span class="progress-count">5</span>
                        <span class="progress-label">Em reparo</span>
                    </li>
                    <li class="step-wizard-item {% if os.status == 'Pronto' %}current-item{% endif %}">
                        <span class="progress-count">6</span>
                        <span class="progress-label">Pronto</span>
                    </li>
                </ul>
            </section>
        </div>
    {% else %}
        <p class="mt-3">Esperando um funcionário se responsabilizar pela sua OS</p>
    {% endif %}
</div>

<script type="text/javascript">
    function renderStars(rating) {
        let stars = '';
        for (let i = 0; i < 5; i++) {
            if (i < rating) {
                stars += '★'; // Estrela preenchida
            } else {
                stars += '☆'; // Estrela vazia
            }
        }
        return stars;
    }
    
    window.onload = function() {
        var ratingElements = document.getElementsByClassName('rating');
        for (var i = 0; i < ratingElements.length; i++) {
            var ratingElement = ratingElements[i];
            var rating = ratingElement.getAttribute('data-rating');
            ratingElement.innerHTML = renderStars(rating);
        }
    }
    </script>
    
{% endblock %}

Projeto/apps/templates/apps/editar_os.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="container editar-os mt-5">
        <div class="row align-items-center">
            <div class="col-md-6 os-details">
                <div class="card glass-card">
                    <div class="card-body">
                        <h2 class="card-title">Número da OS: {{ os.numero }}</h2>
                        <p class="card-text"><strong>Nome do Cliente:</strong> {{ os.perfil_os.nome }}</p>
                        <p class="card-text"><strong>Contato:</strong> {{ os.perfil_os.contato }}</p>
                        <p class="card-text"><strong>Garantia:</strong> {{ os.garantia }}</p>
                        <p class="card-text"><strong>Aparelho:</strong> {{ os.aparelho }}</p>
                        <p class="card-text"><strong>Modelo do aparelho:</strong> {{ os.modelo }}</p>
                        <p class="card-text"><strong>Problema relatado:</strong> {{ os.descricao_problema }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="mensagem_funcionario">Comentários para o Cliente:</label>
                        <textarea id="mensagem_funcionario" name="mensagem_funcionario" class="form-control">{{ os.mensagem_funcionario|default:"" }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="problema_detectado">Problema Detectado:</label>
                        <textarea id="problema_detectado" name="problema_detectado" class="form-control">{{ os.problema_detectado|default:"" }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="status">Status:</label>
                        <select id="status" name="status" class="form-control">
                            <option value="Iniciada" {% if os.status == 'Iniciada' %}selected{% endif %}>Iniciada</option>
                            <option value="Em_analise" {% if os.status == 'Em_analise' %}selected{% endif %}>Em análise</option>
                            <option id="aguardando-peca" value="Aguardando_peca" {% if os.status == 'Aguardando_peca' %}selected{% endif %}>Aguardando peça</option>
                            <option value="Aguardando_reparo" {% if os.status == 'Aguardando_reparo' %}selected{% endif %}>Aguardando reparo</option>
                            <option value="Em_reparo" {% if os.status == 'Em_reparo' %}selected{% endif %}>Em reparo</option>
                            <option value="Pronto" {% if os.status == 'Pronto' %}selected{% endif %}>Pronto</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="tipo_atendimento">Tipo de Atendimento:</label>
                        <select id="tipo_atendimento" name="tipo_atendimento" class="form-control">
                            <option value="-" {% if os.tipo_atendimento == '-' %}selected{% endif %}>-</option>
                            <option value="FON" {% if os.tipo_atendimento == 'FON' %}selected{% endif %}>Fora on site</option>
                            <option value="FB" {% if os.tipo_atendimento == 'FB' %}selected{% endif %}>Fora Balcão</option>
                            <option value="GS" {% if os.tipo_atendimento == 'GS' %}selected{% endif %}>Garantia serviço</option>
                            <option value="GB" {% if os.tipo_atendimento == 'GB' %}selected{% endif %}>Garantia balcão</option>
                            <option id="GON" value="GON" {% if os.tipo_atendimento == 'GON' %}selected{% endif %}>Garantia on site</option>
                            <option value="GIN" {% if os.tipo_atendimento == 'GIN' %}selected{% endif %}>Garantia instalação</option>
                            <option value="GRIN" {% if os.tipo_atendimento == 'GRIN' %}selected{% endif %}>Garantia reincidência</option>
                        </select>
                    </div>                    
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Projeto/apps/templates/apps/funcionario_cadastro.html
{% extends 'global/base_logins.html' %}

{% block body %}
    <div class="container">
        <h2>FAÇA SEU CADASTRO</h2>

        <form class="login cadastro-form" action="{% if form_type == 'cliente' %}{% url 'cliente_cadastro' %}{% elif form_type == 'funcionario' %}{% url 'funcionario_cadastro' %}{% endif %}" method="post">
            {% csrf_token %}
            
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <input type="text" placeholder="Nome" id="id_nome" name="nome" required>
            
            <input type="text" placeholder="Email da Empresa" id="id_email" name="email" required>

            <input type="text" placeholder="Username" id="id_username" name="username" required>
        
            <input type="password" placeholder="Senha" id="id_senha" name="senha" required>

            <input type="password"  placeholder="Confirmar Senha" id="id_confirmar_senha" name="confirmar_senha" >

            <input type='submit' value='Cadastrar' class='btn btn-light'>

        </form>
    </div>
{% endblock %}